- name: checking the number is greater than or not
  hosts: local
  connection: local
  vars:
    NUM: 5
  
  tasks:
  - name: printing the small number
    ansible.builtin.debug:
      msg: "the number {{NUM}} is less than 10" 
    when: NUM < 10
  
  - name: printing the large num
    ansible.builtin.debug:
      msg: "the number {{NUM}} is greater than 10"
    when: NUM > 10