- name: entering values using prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: USERNAME
      prompt: please enter ur user name 
      private: false

    - name: PASSWORD
      prompt: enter Password
      private: false

  tasks:
  - name: printing user info
    ansible.builtin.debug:
      msg: "hello the user name is: {{USERNAME}}, password is: {{PASSWORD}}"
