- name: mongodb server installation
  become: yes
  hosts: mongodb
  connection: local
  tasks:
  - name: copy mongodb
    ansible.builtin.copy:
      source: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.package:
      name: mongo-org
      state: present

  - name: enabling the service
    ansible.builtin.service:
      name: mongodb
      enable: yes

  - name: starting the service
    ansible.builtin.service:
      name: mongodb
      state: started

  - name: allowing remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.0'
      replace: '0.0.0.0'

  - name: restarting the service
    ansible.builtin.service:
      name: mongodb
      state: restarted

  

